name: Build ZMK firmware

on:
  push:
    paths:
      - build.yaml
      - 'config/**'
      - 'boards/**'
      - .github/workflows/build.yml

  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'    # Runs at 10:00 UTC every Monday

permissions:
  contents: write

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    needs: build
    uses: filterpaper/scripts/.github/workflows/publish-artifact.yml@main
    with:
      release_name: ZMK Firmware
      release_tag: latest

  purge:
    if: github.event_name == 'schedule'
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main