# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - "boards/arm/geulis/*.keymap"
      - "boards/arm/geulis/*.dtsi"
      - keymap-drawer/geulis.yaml
      - .github/workflows/draw-keymaps.yml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # allow workflow to commit to the repo
    with:
      keymap_patterns: "boards/arm/geulis/*.keymap"  # config file, ignored if not exists
      output_folder: "keymap-drawer"            # path to save produced SVG and keymap YAML files
      json_path: keymap-drawer/layouts

